#!/usr/bin/env python3
"""
Unit tests for init_project.py

Tests the deterministic scaffold generation. Note: long-task-guide.md is
NOT generated by init_project.py — it is created by the LLM during the
Initializer phase. See test_validate_guide.py for guide validation tests.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile

SCRIPT_PATH = os.path.join(os.path.dirname(__file__), "..", "skills", "long-task-init", "scripts", "init_project.py")


def run_init(project_name, output_dir, extra_args=None):
    """Run init_project.py, return (exit_code, stdout, stderr)."""
    cmd = [sys.executable, SCRIPT_PATH, project_name, "--path", output_dir]
    if extra_args:
        cmd.extend(extra_args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode, result.stdout, result.stderr


def test_creates_all_artifacts():
    """init_project.py should create all expected files and directories."""
    tmp = tempfile.mkdtemp()
    try:
        code, stdout, _ = run_init("test-project", tmp)
        assert code == 0, f"Expected exit 0, got {code}"

        expected_files = [
            "feature-list.json",
            "CLAUDE.md",
            "AGENTS.md",
            "task-progress.md",
            "RELEASE_NOTES.md",
            os.path.join("examples", "README.md"),
        ]
        for f in expected_files:
            path = os.path.join(tmp, f)
            assert os.path.exists(path), f"Missing: {f}"

        expected_dirs = [
            "scripts",
            "examples",
            os.path.join("docs", "plans"),
        ]
        for d in expected_dirs:
            path = os.path.join(tmp, d)
            assert os.path.isdir(path), f"Missing directory: {d}"
    finally:
        shutil.rmtree(tmp)


def test_does_not_create_guide():
    """init_project.py should NOT create LLM-generated files (guide)."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fname = "long-task-guide.md"
        assert not os.path.exists(os.path.join(tmp, fname)), \
            f"{fname} should NOT be generated by init_project.py"
    finally:
        shutil.rmtree(tmp)


def test_feature_list_is_valid_json():
    """feature-list.json should be valid JSON with correct structure."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "project" in data, "Missing 'project' key"
        assert data["project"] == "test-project"
        assert "features" in data, "Missing 'features' key"
        assert isinstance(data["features"], list)
    finally:
        shutil.rmtree(tmp)


def test_scripts_dir_created():
    """scripts/ directory should be created."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "scripts"))
    finally:
        shutil.rmtree(tmp)


def test_routing_helper_scripts_copied():
    """phase_route.py / count_pending.py / feature_paths.py should be copied into scripts/."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        scripts_dir = os.path.join(tmp, "scripts")
        for name in ("phase_route.py", "count_pending.py", "feature_paths.py"):
            assert os.path.isfile(os.path.join(scripts_dir, name)), (
                f"scripts/{name} should be copied by init_project.py"
            )
    finally:
        shutil.rmtree(tmp)


def test_docs_plans_dir_created():
    """docs/plans/ directory should be created."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "docs", "plans"))
    finally:
        shutil.rmtree(tmp)


def test_examples_dir_created():
    """examples/ directory should be created with README.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "examples"))
        readme = os.path.join(tmp, "examples", "README.md")
        assert os.path.exists(readme)
        with open(readme, "r", encoding="utf-8") as f:
            content = f.read()
        assert "test-project" in content
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_tech_stack():
    """feature-list.json should contain tech_stack with TODO placeholders."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "tech_stack" in data, "Missing 'tech_stack' key"
        ts = data["tech_stack"]
        assert ts["language"] == "TODO"
        assert ts["test_framework"] == "TODO"
        assert ts["coverage_tool"] == "TODO"
        assert ts["mutation_tool"] == "TODO"
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_no_quality_gates():
    """feature-list.json should NOT contain quality_gates (removed from pipeline)."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "quality_gates" not in data, "quality_gates should not be present"
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_constraints():
    """feature-list.json should contain constraints as empty array."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "constraints" in data, "Missing 'constraints' key"
        assert isinstance(data["constraints"], list)
        assert len(data["constraints"]) == 0
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_assumptions():
    """feature-list.json should contain assumptions as empty array."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "assumptions" in data, "Missing 'assumptions' key"
        assert isinstance(data["assumptions"], list)
        assert len(data["assumptions"]) == 0
    finally:
        shutil.rmtree(tmp)


def test_task_progress_has_current_state_header():
    """task-progress.md should contain a ## Current State header for session orientation."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        tp_path = os.path.join(tmp, "task-progress.md")
        with open(tp_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "## Current State" in content, "task-progress.md must have ## Current State header"
        assert "Progress:" in content, "## Current State must include Progress field"
    finally:
        shutil.rmtree(tmp)


def test_lang_preset_fills_tools():
    """--lang python should auto-fill pytest, pytest-cov, mutmut."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, ["--lang", "python"])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "python"
        assert ts["test_framework"] == "pytest"
        assert ts["coverage_tool"] == "pytest-cov"
        assert ts["mutation_tool"] == "mutmut"
    finally:
        shutil.rmtree(tmp)


def test_lang_preset_javascript():
    """--lang javascript should auto-fill jest, c8-jest, stryker."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, ["--lang", "javascript"])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "javascript"
        assert ts["test_framework"] == "jest"
        assert ts["coverage_tool"] == "c8-jest"
        assert ts["mutation_tool"] == "stryker"
    finally:
        shutil.rmtree(tmp)


def test_tool_override_with_preset():
    """Explicit --coverage-tool should override the language preset."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, [
            "--lang", "typescript",
            "--coverage-tool", "nyc"
        ])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "typescript"
        assert ts["coverage_tool"] == "nyc", f"Expected nyc override, got {ts['coverage_tool']}"
        assert ts["test_framework"] == "vitest"  # from preset
        assert ts["mutation_tool"] == "stryker"   # from preset
    finally:
        shutil.rmtree(tmp)


def test_creates_claude_md():
    """CLAUDE.md should be created with marker and reference when it does not exist."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        assert os.path.exists(cm_path), "CLAUDE.md should be created"
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "test-project" in content, "Should contain project name"
    finally:
        shutil.rmtree(tmp)


def test_appends_to_existing_claude_md():
    """CLAUDE.md should be appended to (not overwritten) when it already exists."""
    tmp = tempfile.mkdtemp()
    try:
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "w", encoding="utf-8") as f:
            f.write("# Existing Content\n\nSome existing instructions.\n")
        run_init("test-project", tmp)
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert content.startswith("# Existing Content"), "Original content should be preserved"
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "feature-list.json" in content, "Should reference feature list"
    finally:
        shutil.rmtree(tmp)


def test_idempotent_claude_md():
    """Running init twice should not duplicate the reference in CLAUDE.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        count = content.count("<!-- long-task-agent -->")
        assert count == 1, f"Marker should appear exactly once, found {count}"
    finally:
        shutil.rmtree(tmp)


def test_claude_md_contains_key_file_references():
    """CLAUDE.md inject body should reference router + phase skills + signal files."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "feature-list.json" in content, "Should reference feature list"
        assert "phase_route.py" in content, "Should reference router script (single source of truth)"
        assert "long-task-work-design" in content, "Should reference design phase skill"
        assert "long-task-work-tdd" in content, "Should reference TDD phase skill"
        assert "bugfix-request.json" in content, "Should reference hotfix signal"
        assert "increment-request.json" in content, "Should reference increment signal"
    finally:
        shutil.rmtree(tmp)


def test_creates_agents_md():
    """AGENTS.md should be created with marker and reference when it does not exist."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        assert os.path.exists(am_path), "AGENTS.md should be created"
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "test-project" in content, "Should contain project name"
    finally:
        shutil.rmtree(tmp)


def test_appends_to_existing_agents_md():
    """AGENTS.md should be appended to (not overwritten) when it already exists."""
    tmp = tempfile.mkdtemp()
    try:
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "w", encoding="utf-8") as f:
            f.write("# Existing Content\n\nSome existing instructions.\n")
        run_init("test-project", tmp)
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert content.startswith("# Existing Content"), "Original content should be preserved"
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "feature-list.json" in content, "Should reference feature list"
    finally:
        shutil.rmtree(tmp)


def test_idempotent_agents_md():
    """Running init twice should not duplicate the reference in AGENTS.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        count = content.count("<!-- long-task-agent -->")
        assert count == 1, f"Marker should appear exactly once, found {count}"
    finally:
        shutil.rmtree(tmp)


def test_agents_md_contains_key_file_references():
    """AGENTS.md inject body should reference router + phase skills + signal files."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "feature-list.json" in content, "Should reference feature list"
        assert "phase_route.py" in content, "Should reference router script"
        assert "long-task-work-design" in content, "Should reference design phase skill"
        assert "long-task-work-tdd" in content, "Should reference TDD phase skill"
        assert "bugfix-request.json" in content, "Should reference hotfix signal"
        assert "increment-request.json" in content, "Should reference increment signal"
    finally:
        shutil.rmtree(tmp)


def test_stdout_mentions_llm_todo():
    """init_project.py output should remind about LLM-generated files."""
    tmp = tempfile.mkdtemp()
    try:
        _, stdout, _ = run_init("test-project", tmp)
        assert "long-task-guide.md" in stdout, "Should mention guide as LLM TODO"
    finally:
        shutil.rmtree(tmp)


def test_commit_msg_hook_not_copied_by_init():
    """commit-msg-hook should NOT be in scripts/ — it is installed by the session-start hook."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        hook_path = os.path.join(tmp, "scripts", "commit-msg-hook")
        assert not os.path.exists(hook_path), \
            "scripts/commit-msg-hook should NOT be created by init_project.py"
    finally:
        shutil.rmtree(tmp)


if __name__ == "__main__":
    tests = [
        test_creates_all_artifacts,
        test_does_not_create_guide_or_init_scripts,
        test_feature_list_is_valid_json,
        test_scripts_dir_created,
        test_routing_helper_scripts_copied,
        test_docs_plans_dir_created,
        test_examples_dir_created,
        test_feature_list_has_tech_stack,
        test_feature_list_has_no_quality_gates,
        test_lang_preset_fills_tools,
        test_lang_preset_javascript,
        test_tool_override_with_preset,
        test_creates_claude_md,
        test_appends_to_existing_claude_md,
        test_idempotent_claude_md,
        test_creates_agents_md,
        test_appends_to_existing_agents_md,
        test_idempotent_agents_md,
        test_agents_md_contains_key_file_references,
        test_stdout_mentions_llm_todo,
        test_feature_list_has_constraints,
        test_feature_list_has_assumptions,
    ]
    passed = 0
    failed = 0
    for test in tests:
        try:
            test()
            print(f"  PASS: {test.__name__}")
            passed += 1
        except AssertionError as e:
            print(f"  FAIL: {test.__name__}: {e}")
            failed += 1
        except Exception as e:
            print(f"  ERROR: {test.__name__}: {e}")
            failed += 1

    print(f"\n{passed} passed, {failed} failed")
    sys.exit(1 if failed > 0 else 0)
