#!/usr/bin/env python3
"""
Unit tests for init_project.py

Tests the deterministic scaffold generation. Note: long-task-guide.md and
init.sh/init.ps1 are NOT generated by init_project.py — they are created
by the LLM during the Initializer phase. See test_validate_guide.py for
guide validation tests.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile

SCRIPT_PATH = os.path.join(os.path.dirname(__file__), "..", "skills", "long-task-init", "scripts", "init_project.py")


def run_init(project_name, output_dir, extra_args=None):
    """Run init_project.py, return (exit_code, stdout, stderr)."""
    cmd = [sys.executable, SCRIPT_PATH, project_name, "--path", output_dir]
    if extra_args:
        cmd.extend(extra_args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode, result.stdout, result.stderr


def test_creates_all_artifacts():
    """init_project.py should create all expected files and directories."""
    tmp = tempfile.mkdtemp()
    try:
        code, stdout, _ = run_init("test-project", tmp)
        assert code == 0, f"Expected exit 0, got {code}"

        expected_files = [
            "feature-list.json",
            "CLAUDE.md",
            "AGENTS.md",
            "task-progress.md",
            "RELEASE_NOTES.md",
            os.path.join("examples", "README.md"),
        ]
        for f in expected_files:
            path = os.path.join(tmp, f)
            assert os.path.exists(path), f"Missing: {f}"

        expected_dirs = [
            "scripts",
            "examples",
            os.path.join("docs", "plans"),
        ]
        for d in expected_dirs:
            path = os.path.join(tmp, d)
            assert os.path.isdir(path), f"Missing directory: {d}"
    finally:
        shutil.rmtree(tmp)


def test_does_not_create_guide_or_init_scripts():
    """init_project.py should NOT create LLM-generated files (guide, init scripts)."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        for fname in [
            "long-task-guide.md",
            "init.sh", "init.ps1",
        ]:
            assert not os.path.exists(os.path.join(tmp, fname)), \
                f"{fname} should NOT be generated by init_project.py"
    finally:
        shutil.rmtree(tmp)


def test_feature_list_is_valid_json():
    """feature-list.json should be valid JSON with correct structure."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "project" in data, "Missing 'project' key"
        assert data["project"] == "test-project"
        assert "features" in data, "Missing 'features' key"
        assert isinstance(data["features"], list)
    finally:
        shutil.rmtree(tmp)


def test_scripts_dir_created():
    """scripts/ directory should be created."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "scripts"))
    finally:
        shutil.rmtree(tmp)


def test_docs_plans_dir_created():
    """docs/plans/ directory should be created."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "docs", "plans"))
    finally:
        shutil.rmtree(tmp)


def test_examples_dir_created():
    """examples/ directory should be created with README.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        assert os.path.isdir(os.path.join(tmp, "examples"))
        readme = os.path.join(tmp, "examples", "README.md")
        assert os.path.exists(readme)
        with open(readme, "r", encoding="utf-8") as f:
            content = f.read()
        assert "test-project" in content
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_tech_stack():
    """feature-list.json should contain tech_stack with TODO placeholders."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "tech_stack" in data, "Missing 'tech_stack' key"
        ts = data["tech_stack"]
        assert ts["language"] == "TODO"
        assert ts["test_framework"] == "TODO"
        assert ts["coverage_tool"] == "TODO"
        assert ts["mutation_tool"] == "TODO"
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_quality_gates():
    """feature-list.json should contain quality_gates with default thresholds."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "quality_gates" in data, "Missing 'quality_gates' key"
        qg = data["quality_gates"]
        assert qg["line_coverage_min"] == 90
        assert qg["branch_coverage_min"] == 80
        assert qg["mutation_score_min"] == 80
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_required_configs():
    """feature-list.json should contain required_configs as empty array."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "required_configs" in data, "Missing 'required_configs' key"
        assert isinstance(data["required_configs"], list)
        assert len(data["required_configs"]) == 0
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_constraints():
    """feature-list.json should contain constraints as empty array."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "constraints" in data, "Missing 'constraints' key"
        assert isinstance(data["constraints"], list)
        assert len(data["constraints"]) == 0
    finally:
        shutil.rmtree(tmp)


def test_feature_list_has_assumptions():
    """feature-list.json should contain assumptions as empty array."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        assert "assumptions" in data, "Missing 'assumptions' key"
        assert isinstance(data["assumptions"], list)
        assert len(data["assumptions"]) == 0
    finally:
        shutil.rmtree(tmp)


def test_task_progress_has_current_state_header():
    """task-progress.md should contain a ## Current State header for session orientation."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        tp_path = os.path.join(tmp, "task-progress.md")
        with open(tp_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "## Current State" in content, "task-progress.md must have ## Current State header"
        assert "Progress:" in content, "## Current State must include Progress field"
    finally:
        shutil.rmtree(tmp)


def test_lang_preset_fills_tools():
    """--lang python should auto-fill pytest, pytest-cov, mutmut."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, ["--lang", "python"])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "python"
        assert ts["test_framework"] == "pytest"
        assert ts["coverage_tool"] == "pytest-cov"
        assert ts["mutation_tool"] == "mutmut"
    finally:
        shutil.rmtree(tmp)


def test_custom_thresholds():
    """--line-cov, --branch-cov, --mutation-score should override defaults."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, [
            "--lang", "java",
            "--line-cov", "85",
            "--branch-cov", "75",
            "--mutation-score", "70"
        ])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        qg = data["quality_gates"]
        assert qg["line_coverage_min"] == 85, f"Expected 85, got {qg['line_coverage_min']}"
        assert qg["branch_coverage_min"] == 75, f"Expected 75, got {qg['branch_coverage_min']}"
        assert qg["mutation_score_min"] == 70, f"Expected 70, got {qg['mutation_score_min']}"
        # Also verify Java preset was applied
        ts = data["tech_stack"]
        assert ts["language"] == "java"
        assert ts["test_framework"] == "junit"
        assert ts["coverage_tool"] == "jacoco"
        assert ts["mutation_tool"] == "pitest"
    finally:
        shutil.rmtree(tmp)


def test_lang_preset_javascript():
    """--lang javascript should auto-fill jest, c8-jest, stryker."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, ["--lang", "javascript"])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "javascript"
        assert ts["test_framework"] == "jest"
        assert ts["coverage_tool"] == "c8-jest"
        assert ts["mutation_tool"] == "stryker"
    finally:
        shutil.rmtree(tmp)


def test_tool_override_with_preset():
    """Explicit --coverage-tool should override the language preset."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp, [
            "--lang", "typescript",
            "--coverage-tool", "nyc"
        ])
        fl_path = os.path.join(tmp, "feature-list.json")
        with open(fl_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        ts = data["tech_stack"]
        assert ts["language"] == "typescript"
        assert ts["coverage_tool"] == "nyc", f"Expected nyc override, got {ts['coverage_tool']}"
        assert ts["test_framework"] == "vitest"  # from preset
        assert ts["mutation_tool"] == "stryker"   # from preset
    finally:
        shutil.rmtree(tmp)


def test_creates_claude_md():
    """CLAUDE.md should be created with marker and reference when it does not exist."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        assert os.path.exists(cm_path), "CLAUDE.md should be created"
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "test-project" in content, "Should contain project name"
    finally:
        shutil.rmtree(tmp)


def test_appends_to_existing_claude_md():
    """CLAUDE.md should be appended to (not overwritten) when it already exists."""
    tmp = tempfile.mkdtemp()
    try:
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "w", encoding="utf-8") as f:
            f.write("# Existing Content\n\nSome existing instructions.\n")
        run_init("test-project", tmp)
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert content.startswith("# Existing Content"), "Original content should be preserved"
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "feature-list.json" in content, "Should reference feature list"
    finally:
        shutil.rmtree(tmp)


def test_idempotent_claude_md():
    """Running init twice should not duplicate the reference in CLAUDE.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        count = content.count("<!-- long-task-agent -->")
        assert count == 1, f"Marker should appear exactly once, found {count}"
    finally:
        shutil.rmtree(tmp)


def test_claude_md_contains_key_file_references():
    """CLAUDE.md should reference key project files: feature-list.json, task-progress.md, docs/plans."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        cm_path = os.path.join(tmp, "CLAUDE.md")
        with open(cm_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "feature-list.json" in content, "Should reference feature list"
        assert "task-progress.md" in content, "Should reference progress log"
        assert "docs/plans" in content, "Should reference docs/plans for SRS/design"
        assert "increment-request.json" in content, "Should reference increment signal file"
    finally:
        shutil.rmtree(tmp)


def test_creates_agents_md():
    """AGENTS.md should be created with marker and reference when it does not exist."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        assert os.path.exists(am_path), "AGENTS.md should be created"
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "test-project" in content, "Should contain project name"
    finally:
        shutil.rmtree(tmp)


def test_appends_to_existing_agents_md():
    """AGENTS.md should be appended to (not overwritten) when it already exists."""
    tmp = tempfile.mkdtemp()
    try:
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "w", encoding="utf-8") as f:
            f.write("# Existing Content\n\nSome existing instructions.\n")
        run_init("test-project", tmp)
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert content.startswith("# Existing Content"), "Original content should be preserved"
        assert "<!-- long-task-agent -->" in content, "Should contain marker"
        assert "feature-list.json" in content, "Should reference feature list"
    finally:
        shutil.rmtree(tmp)


def test_idempotent_agents_md():
    """Running init twice should not duplicate the reference in AGENTS.md."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        count = content.count("<!-- long-task-agent -->")
        assert count == 1, f"Marker should appear exactly once, found {count}"
    finally:
        shutil.rmtree(tmp)


def test_agents_md_contains_key_file_references():
    """AGENTS.md should reference key project files: feature-list.json, task-progress.md, docs/plans."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        am_path = os.path.join(tmp, "AGENTS.md")
        with open(am_path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "feature-list.json" in content, "Should reference feature list"
        assert "task-progress.md" in content, "Should reference progress log"
        assert "docs/plans" in content, "Should reference docs/plans"
        assert "increment-request.json" in content, "Should reference increment signal file"
    finally:
        shutil.rmtree(tmp)


def test_stdout_mentions_llm_todo():
    """init_project.py output should remind about LLM-generated files."""
    tmp = tempfile.mkdtemp()
    try:
        _, stdout, _ = run_init("test-project", tmp)
        assert "long-task-guide.md" in stdout, "Should mention guide as LLM TODO"
        assert "init.sh" in stdout, "Should mention init.sh as LLM TODO"
    finally:
        shutil.rmtree(tmp)


def test_commit_msg_hook_not_copied_by_init():
    """commit-msg-hook should NOT be in scripts/ — it is installed by the session-start hook."""
    tmp = tempfile.mkdtemp()
    try:
        run_init("test-project", tmp)
        hook_path = os.path.join(tmp, "scripts", "commit-msg-hook")
        assert not os.path.exists(hook_path), \
            "scripts/commit-msg-hook should NOT be created by init_project.py"
    finally:
        shutil.rmtree(tmp)


if __name__ == "__main__":
    tests = [
        test_creates_all_artifacts,
        test_does_not_create_guide_or_init_scripts,
        test_feature_list_is_valid_json,
        test_scripts_dir_created,
        test_docs_plans_dir_created,
        test_examples_dir_created,
        test_feature_list_has_tech_stack,
        test_feature_list_has_quality_gates,
        test_feature_list_has_required_configs,
        test_lang_preset_fills_tools,
        test_lang_preset_javascript,
        test_custom_thresholds,
        test_tool_override_with_preset,
        test_creates_claude_md,
        test_appends_to_existing_claude_md,
        test_idempotent_claude_md,
        test_creates_agents_md,
        test_appends_to_existing_agents_md,
        test_idempotent_agents_md,
        test_agents_md_contains_key_file_references,
        test_stdout_mentions_llm_todo,
        test_feature_list_has_constraints,
        test_feature_list_has_assumptions,
    ]
    passed = 0
    failed = 0
    for test in tests:
        try:
            test()
            print(f"  PASS: {test.__name__}")
            passed += 1
        except AssertionError as e:
            print(f"  FAIL: {test.__name__}: {e}")
            failed += 1
        except Exception as e:
            print(f"  ERROR: {test.__name__}: {e}")
            failed += 1

    print(f"\n{passed} passed, {failed} failed")
    sys.exit(1 if failed > 0 else 0)
